### ISSUE TITLE
Source code availability

### ISSUE THREAD

**Issue by gibranrosa** [thany-noroozpour/diesel-odbc#1]
Hello!

Could you provide the source code, if it is open, even though it is incomplete?

I am interested in help out.

Thanks!

**Comment by thany-noroozpour** [comment]
Hello @gibranrosa , 
Unfortunately I can't, it was part of an enterprise application and because of some overhastiness, it happened to hold some of my client's business related code in it. I hoped someday, I can pull out the code from that project, but Diesel changed a lot compare to the day I have written it. Right now, I don't have enough time to make it feasible.

I completely forgot about this repository. I think, it is the time to cleanup some of my old repositories. 

However sorry for inconvenience.
